/**
 * .imagine <prompt> — AI image generator
 *
 * Order of providers (first success wins):
 *   1. Pollinations (KEYLESS)  — real AI image generation, no API key needed
 *   2. Unsplash                — real-photo fallback (needs UNSPLASH_ACCESS_KEY)
 *
 * Aliases: .aiimg, .genimage, .create
 */
const axios = require('axios');
const { generateImage } = require('../../utils/smartAI');

const UNSPLASH_ACCESS_KEY = process.env.UNSPLASH_ACCESS_KEY || '';

async function tryPollinations(prompt) {
    const buf = await generateImage(prompt);
    if (!buf) return null;
    return { buf, credit: null, model: 'Pollinations AI (Flux)' };
}

async function tryUnsplash(prompt) {
    if (!UNSPLASH_ACCESS_KEY) return null;
    try {
        const { data } = await axios.get('https://api.unsplash.com/photos/random', {
            params: { query: prompt, orientation: 'squarish', count: 1 },
            headers: { Authorization: `Client-ID ${UNSPLASH_ACCESS_KEY}` },
            timeout: 30000,
        });
        const item = Array.isArray(data) ? data[0] : data;
        const url  = item?.urls?.regular || item?.urls?.full || item?.urls?.small;
        if (!url) return null;
        const res = await axios.get(url, { responseType: 'arraybuffer', timeout: 60000 });
        const buf = Buffer.from(res.data);
        if (!buf || buf.length < 1024) return null;
        return {
            buf,
            credit: item?.user?.name ? `Photo by ${item.user.name} on Unsplash` : 'Unsplash',
            model: 'Unsplash',
        };
    } catch (e) {
        console.error('[imagine] Unsplash failed:', e.message);
        return null;
    }
}

module.exports = {
    name: 'imagine',
    aliases: ['aiimg', 'genimage', 'create'],
    description: 'Generate an AI image from text (.imagine <prompt>)',
    category: 'ai',

    async execute({ sock, msg, from, reply, args }) {
        if (!args.length) {
            return reply(
                `🎨 *AI Image Generator*\n\n` +
                `Usage: .imagine <description>\n` +
                `Example: .imagine a cat wearing a spacesuit on the moon`
            );
        }

        const prompt = args.join(' ').trim();
        await reply('🎨 *Generating image...* please wait.');

        let r = await tryPollinations(prompt);
        if (!r) r = await tryUnsplash(prompt);

        if (!r) {
            return reply('❌ Image generation is temporarily unavailable. Please try again shortly.');
        }

        const creditLine = r.credit ? `\nCredit: ${r.credit}` : '';
        try {
            await sock.sendMessage(from, {
                image: r.buf,
                caption: `🎨 *Image Result*\n\nPrompt: ${prompt}\nSource: ${r.model}${creditLine}\n\n> Generated by SUKUNA MD`,
            }, { quoted: msg });
        } catch (err) {
            reply(`❌ Failed to send image: ${err.message}`);
        }
    },
};
