/**
 * PixelArt AI Command
 * Usage: .pixelart <prompt>
 */

const axios = require('axios');

module.exports = {
    name: 'pixelart',
    description: 'Generate a pixel art image',
    category: 'media',
    async execute({ sock, msg, from, reply, args }) {
        const prompt = args.join(' ');
        if (!prompt) {
            return reply('🎨 Please provide a prompt for the pixel art.\nExample: .pixelart a cat');
        }

        try {
            // Using Pollinations AI with pixel art model for better results
            const imageUrl = `https://image.pollinations.ai/prompt/pixel art of ${encodeURIComponent(prompt)}?nologo=true&model=flux-pixelart`;
            
            await sock.sendMessage(from, {
                image: { url: imageUrl },
                caption: `🎨 *Pixel Art:* ${prompt}\n\n> Generated by SUKUNA MD`
            }, { quoted: msg });
        } catch (err) {
            console.error('[pixelart]', err.message);
            
            // Fallback to basic imagine API
            try {
                const fallbackUrl = `https://image.pollinations.ai/prompt/pixel art of ${encodeURIComponent(prompt)}?nologo=true`;
                await sock.sendMessage(from, {
                    image: { url: fallbackUrl },
                    caption: `🎨 *Pixel Art:* ${prompt}\n\n> Generated by SUKUNA MD`
                }, { quoted: msg });
            } catch (fallbackErr) {
                reply('❌ Failed to generate pixel art.');
            }
        }
    }
};
