'use strict';

const { sendRichHtml } = require('../../utils/genaiRich');

function dashHtml() {
    return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no"><style>
*{box-sizing:border-box}html,body{margin:0;width:100%;overflow:hidden;background:transparent;font-family:Arial,sans-serif}body{padding:5px;background:linear-gradient(155deg,#061b32,#092a3b 55%,#031322)}.card{padding:10px;border:2px solid #18b8d8;border-radius:22px;background:linear-gradient(145deg,#061c31,#0b4053 52%,#061728);color:#e8fbff;box-shadow:inset 0 0 0 3px #07324a,0 8px 20px #000b}.brand{display:flex;align-items:center;gap:8px}.swirl{display:grid;place-items:center;width:34px;height:34px;border-radius:50%;color:#11ddff;font-size:28px;font-weight:900;text-shadow:0 0 10px #08cfff}.title{color:#65e9ff;font:bold 23px Impact,Arial Black,sans-serif;letter-spacing:1px;text-shadow:0 0 12px #008fcb}.sub{margin:0 0 7px 42px;color:#a4e4ed;font:10px monospace;letter-spacing:2px}.stats{display:grid;grid-template-columns:1.1fr 1fr 1fr;gap:5px;margin-bottom:7px}.stat{padding:5px 2px;text-align:center;border:1px solid #237c9d;border-radius:8px;background:#061827;color:#82bfd0;font:bold 9px monospace}.stat b{display:block;margin-top:2px;color:#ffdf58;font-size:15px}.arena{position:relative;border:3px solid #147ea8;border-radius:15px;background:#54b8e6;box-shadow:inset 0 0 22px #001c35;overflow:hidden}.arena canvas{display:block;width:100%;height:265px;touch-action:none}.hud{position:absolute;top:7px;left:9px;right:9px;display:flex;justify-content:space-between;color:#eaffff;font:bold 10px monospace;text-shadow:0 1px 3px #00334d;pointer-events:none}.progress{position:absolute;left:10px;right:10px;bottom:8px;height:7px;border-radius:8px;background:#063b4d99;border:1px solid #77eaff77;pointer-events:none}.progress i{display:block;height:100%;width:0;border-radius:8px;background:linear-gradient(90deg,#fff36a,#ffd32b,#ff7c31);transition:width .2s}.message{min-height:31px;margin:7px 2px 6px;display:grid;place-items:center;border:1px solid #237c9d;border-radius:8px;background:#051a29;color:#e4fbff;font:bold 11px monospace;text-align:center}.controls{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px}.controls button{height:43px;border:2px solid #176c8d;border-radius:12px;color:#062033;background:linear-gradient(#ffe873,#e9a91e);font-weight:900;font-size:15px;box-shadow:inset 0 2px #fff8ad}.controls #jump{background:linear-gradient(#56d7ff,#168de0);color:#fff;border-color:#68ddff;box-shadow:inset 0 2px #b4f3ff}.controls #sound{font-size:16px;background:linear-gradient(#174966,#0a283d);color:#bff7ff;box-shadow:none}.controls button:active{transform:scale(.94)}#start{grid-column:1/-1;height:37px;font-size:13px;background:linear-gradient(#18d5e6,#087aa8);color:#fff;border-color:#66f5ff;box-shadow:inset 0 2px #b9ffff}.hint{text-align:center;margin:6px 0 0;color:#8cc9d6;font:9px monospace;line-height:1.35}
</style></head><body><div class="card"><div class="brand"><div class="swirl">◉</div><div class="title">SPEEDY DASH</div></div><div class="sub">EMERALD COAST RUN</div><div class="stats"><div class="stat">RINGS<b id="rings">0</b></div><div class="stat">SCORE<b id="score">0</b></div><div class="stat">BEST<b id="best">0</b></div></div><div class="arena"><canvas id="game" width="640" height="530"></canvas><div class="hud"><span id="distance">DIST 0m</span><span id="stage">COAST 1</span></div><div class="progress"><i id="progress"></i></div></div><div class="message" id="message">Tap START RUN — collect rings and dodge the laser</div><div class="controls"><button id="boost">⚡ BOOST</button><button id="jump">↟ JUMP</button><button id="sound">🔊</button><button id="start">START RUN</button></div><div class="hint">Jump over rocks and red lasers · every 50 rings summons a BOSS · sound/voice can be muted</div></div><script>(function(){
var canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=640,H=530,player={x:120,y:410,vy:0,onGround:true,boost:0,inv:0},running=false,raf=0,last=0,spawnClock=0,ringClock=0,world=0,meters=0,rings=0,score=0,best=0,stage=1,sound=true,objects=[],particles=[],audio=null;
var $=function(id){return document.getElementById(id)},ringsEl=$('rings'),scoreEl=$('score'),bestEl=$('best'),distanceEl=$('distance'),stageEl=$('stage'),messageEl=$('message'),progressEl=$('progress');bestEl.textContent=best;var requestFrame=window.requestAnimationFrame||function(cb){return window.setTimeout(function(){cb(Date.now())},16)},cancelFrame=window.cancelAnimationFrame||function(id){window.clearTimeout(id)};function readBest(){try{return Number(window.localStorage.getItem('speedyDashBest')||0)}catch(_){return 0}}function saveBest(v){try{window.localStorage.setItem('speedyDashBest',String(v))}catch(_){}}best=readBest();bestEl.textContent=best;
function say(t,voice){messageEl.textContent=t;if(voice&&sound&&window.speechSynthesis){try{speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(voice);u.rate=1.2;u.pitch=1.1;speechSynthesis.speak(u)}catch(_){}}}
function beep(freq,dur,type){if(!sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();var o=audio.createOscillator(),g=audio.createGain();o.type=type||'sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch(_){}}
function resize(){var r=canvas.getBoundingClientRect();canvas.width=640;canvas.height=530}window.addEventListener('resize',resize);
function reset(){player={x:120,y:410,vy:0,onGround:true,boost:0,inv:0};objects=[];particles=[];world=0;meters=0;rings=0;score=0;stage=1;spawnClock=0;ringClock=0;updateHud()}
function updateHud(){ringsEl.textContent=rings;scoreEl.textContent=score;bestEl.textContent=best;distanceEl.textContent='DIST '+Math.floor(meters)+'m';stageEl.textContent='COAST '+stage;progressEl.style.width=(rings%50)*2+'%'}
function jump(){if(!running)return;if(player.onGround){player.vy=-470;player.onGround=false;beep(520,.12,'square');say('JUMP!')}}
function boost(){if(!running||player.boost>0)return;player.boost=.75;player.inv=.85;score+=15;beep(180,.18,'sawtooth');say('BOOST!','Boost activated');burst(player.x,player.y,'#ffe43d',12)}
function addObject(type,x,y){objects.push({type:type,x:x,y:y,r:type==='ring'?13:26,hit:false,spin:Math.random()*6})}
function spawn(){var x=W+40,roll=Math.random();if(roll<.38)addObject('ring',x,260+Math.random()*110);else if(roll<.62)addObject('ring',x,340);else if(roll<.82)addObject('rock',x,430);else addObject('laser',x,382)}
function boss(){addObject('boss',W+70,365);say('BOSS INCOMING!','Boss incoming');beep(90,.5,'sawtooth')}
function burst(x,y,color,n){for(var i=0;i<n;i++)particles.push({x:x,y:y,vx:(Math.random()-.5)*180,vy:(Math.random()-.8)*180,life:.6,color:color})}
function collide(o){var px=player.x,py=player.y;return Math.abs(o.x-px)<o.r+25&&Math.abs(o.y-py)<o.r+30}
function hit(o){if(o.hit)return;o.hit=true;if(o.type==='ring'){rings++;score+=10;beep(780,.07,'sine');burst(o.x,o.y,'#ffe45b',5);if(rings%50===0){stage++;boss();say('RING BOSS! 50 rings reached','Boss round')}}else if(player.inv<=0){score=Math.max(0,score-25);player.inv=.8;player.vy=-230;beep(110,.25,'sawtooth');burst(player.x,player.y,'#ff4545',9);say(o.type==='laser'?'LASER HIT — dodge faster':'OOPS! ROCK HIT — keep running','Obstacle hit')}}
function drawBg(){var g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#3f9edd');g.addColorStop(.58,'#8bd9eb');g.addColorStop(.59,'#3b8790');g.addColorStop(1,'#168b60');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';for(var i=0;i<5;i++){var cx=((i*180-world*.12)%760)-70;ctx.globalAlpha=.7;ctx.beginPath();ctx.ellipse(cx,100+(i%2)*35,58,18,0,0,7);ctx.ellipse(cx+42,104+(i%2)*35,45,14,0,0,7);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='#3d7f82';ctx.beginPath();ctx.moveTo(0,330);for(var x=0;x<=W;x+=70)ctx.lineTo(x,280+Math.sin(x*.018+world*.002)*35);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ctx.fillStyle='#169357';ctx.fillRect(0,455,W,75);ctx.fillStyle='#0f6d48';for(var j=0;j<13;j++){var tx=((j*70-world*.3)%720)-40;ctx.beginPath();ctx.moveTo(tx,455);ctx.lineTo(tx+10,405);ctx.lineTo(tx+18,455);ctx.fill()}ctx.strokeStyle='#f3d34a';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(0,446);ctx.lineTo(W,446);ctx.stroke()}
function drawPlayer(){ctx.save();ctx.translate(player.x,player.y);if(player.inv>0&&Math.floor(player.inv*14)%2===0)ctx.globalAlpha=.45;ctx.fillStyle='#263f52';ctx.beginPath();ctx.ellipse(0,4,43,25,0,0,7);ctx.fill();ctx.fillStyle='#ec334c';ctx.beginPath();ctx.arc(16,-13,19,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(21,-17,5,0,7);ctx.fill();ctx.fillStyle='#111';ctx.beginPath();ctx.arc(23,-17,2,0,7);ctx.fill();ctx.strokeStyle='#192f3c';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(-23,21);ctx.lineTo(-34,34);ctx.moveTo(8,23);ctx.lineTo(0,38);ctx.stroke();if(player.boost>0){ctx.fillStyle='#ffe04a';ctx.beginPath();ctx.moveTo(-42,0);ctx.lineTo(-73,12);ctx.lineTo(-50,-8);ctx.fill()}ctx.restore()}
function drawObject(o){ctx.save();ctx.translate(o.x,o.y);o.spin+=.06;if(o.type==='ring'){ctx.rotate(o.spin);ctx.strokeStyle='#ffe36b';ctx.lineWidth=8;ctx.beginPath();ctx.arc(0,0,o.r,0,7);ctx.stroke();ctx.strokeStyle='#fff4aa';ctx.lineWidth=2;ctx.stroke()}else if(o.type==='rock'){ctx.fillStyle='#596877';ctx.beginPath();ctx.ellipse(0,12,38,25,0,0,7);ctx.fill();ctx.fillStyle='#d8324b';ctx.beginPath();ctx.arc(12,-5,16,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(17,-9,4,0,7);ctx.fill()}else if(o.type==='laser'){ctx.fillStyle='#db3157';ctx.fillRect(-42,12,84,10);ctx.shadowBlur=18;ctx.shadowColor='#ff2851';ctx.strokeStyle='#ff335d';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-38,-10);ctx.lineTo(38,-10);ctx.stroke()}else{ctx.fillStyle='#283746';ctx.beginPath();ctx.ellipse(0,10,58,37,0,0,7);ctx.fill();ctx.fillStyle='#f53b54';ctx.beginPath();ctx.arc(22,-15,23,0,7);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(29,-20,6,0,7);ctx.fill();ctx.fillStyle='#ffdf43';ctx.font='bold 16px monospace';ctx.fillText('BOSS',-27,-55)}ctx.restore()}
function draw(){drawBg();objects.forEach(drawObject);particles.forEach(function(p){ctx.globalAlpha=Math.max(0,p.life/.6);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,5,5)});ctx.globalAlpha=1;drawPlayer()}
function frame(t){if(!running)return;var dt=Math.min(.04,(t-last)/1000||.016);last=t;world+=dt*(player.boost>0?360:230);meters+=dt*(player.boost>0?1.8:1);player.boost=Math.max(0,player.boost-dt);player.inv=Math.max(0,player.inv-dt);player.vy+=1100*dt;player.y+=player.vy*dt;if(player.y>=410){player.y=410;player.vy=0;player.onGround=true}spawnClock-=dt;ringClock-=dt;if(spawnClock<=0){spawn();spawnClock=Math.max(.42,.9-stage*.04)-Math.random()*.18}objects.forEach(function(o){o.x-=dt*(player.boost>0?390:250);if(collide(o))hit(o)});objects=objects.filter(function(o){return o.x>-100&&!o.hit});particles.forEach(function(p){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;p.life-=dt});particles=particles.filter(function(p){return p.life>0});if(Math.floor(meters)>0&&Math.floor(meters)%100===0&&Math.floor(meters)!==Math.floor(meters-dt*2)){say('Keep going! '+Math.floor(meters)+' meters','Keep going');beep(660,.08,'sine')}score+=Math.floor(dt*8);best=Math.max(best,score);saveBest(best);updateHud();draw();raf=requestFrame(frame)}
function start(){if(running){running=false;cancelFrame(raf);say('Run paused — tap START RUN to restart');$('start').textContent='START RUN';return}reset();running=true;$('start').textContent='PAUSE RUN';say('Run started — collect rings!','Run started');beep(440,.12,'square');last=(window.performance&&performance.now)?performance.now():Date.now();raf=requestFrame(frame)}
$('jump').onclick=jump;$('boost').onclick=boost;$('start').onclick=start;$('sound').onclick=function(){sound=!sound;$('sound').textContent=sound?'🔊':'🔇';if(sound){beep(600,.1,'sine');say('Sound on')}};document.addEventListener('keydown',function(e){if(e.key==='ArrowUp'||e.key===' ')jump();if(e.key==='b'||e.key==='B'||e.key==='ArrowRight')boost();if(e.key==='Enter')start()});canvas.addEventListener('touchstart',function(e){e.preventDefault();if(e.touches[0].clientX<canvas.getBoundingClientRect().left+canvas.getBoundingClientRect().width/2)jump();else boost()},{passive:false});reset();draw();})();</script></body></html>`;
}

module.exports = {
    name: 'dash',
    aliases: ['speedydash', 'emeraldcoast'],
    description: 'Play Speedy Dash with rings, boosts, jumps, bosses, sound and voice cues',
    usage: '.dash',
    category: 'games',
    async execute({ sock, msg, from, reply }) {
        try {
            await sendRichHtml({ sock, jid: from, quoted: msg, html: dashHtml() });
        } catch (error) {
            console.error('[DASH GenAI]', error.message);
            await reply('Speedy Dash could not open on this client. Please update WhatsApp or run `.dash` again.');
        }
    },
};
